name: assignment-test


on: 
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    unit-test:
        runs-on: ubuntu-latest
        container: czpir/unit-test
        steps:
          - uses: actions/checkout@v2
          - name: Set permissions
            run : git config --global --add safe.directory /__w/assignment-1-rcmb/assignment-1-rcmb
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run unit test
            run: ./unit-test.sh
    full-test:
        runs-on: ubuntu-latest
        container: czpir/assignment1:assignment1
        steps:
          - uses: actions/checkout@v2
          - name: Set permissions
            run : git config --global --add safe.directory /__w/assignment-1-rcmb/assignment-1-rcmb
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Run full test
            run: ./full-test.sh
